apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-demo-rewrite
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "test"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "www.test.com"
      http:
        paths:
          - backend:
              serviceName: canary
              servicePort: 80
            path: /rewrite(/|$)(.*)
  tls:
    - secretName: tls-secret
