apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: c1
  template:
    metadata:
      labels:
        app: nginx
        component: c1
    spec:
      containers:
        - image: xishengcai/canary
          imagePullPolicy: IfNotPresent
          name: canary
          ports:
            - containerPort: 80
              name: port
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-c1
  namespace: test
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: c1
  sessionAffinity: None
  type: NodePort
