apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ssl
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "test"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "test/ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: web-c1
              servicePort: 80
            path: /hello
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "test"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "test/ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  name: rewrite
  namespace: test
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: web-c1
              servicePort: 80
            path: /app(/|$)(.*)
  tls:
    - secretName: tls-secret
