apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-subpath-2
mountOptions:
  - nolock,tcp,noresvport
  - vers=3
parameters:
  volumeAs: subpath
  server: "12237f48e9f-nrw60.cn-hongkong.nas.aliyuncs.com"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Delete
deleteVolume: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-csi-pvc-subpath-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-nas-subpath-2
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subpath-nas-2
  labels:
    app: subpath-nas-2
spec:
  selector:
    matchLabels:
      app: subpath-nas-2
  template:
    metadata:
      labels:
        app: subpath-nas-2
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nas-pvc
              mountPath: "/data"
      volumes:
        - name: nas-pvc
          persistentVolumeClaim:
            claimName: nas-csi-pvc-subpath-2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-subpath-3
mountOptions:
  - nolock,tcp,noresvport
  - vers=3
parameters:
  volumeAs: subpath
  server: "12237f48e9f-nrw60.cn-hongkong.nas.aliyuncs.com"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-csi-pvc-subpath-3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-nas-subpath-2
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subpath-nas-3
  labels:
    app: subpath-nas-3
spec:
  selector:
    matchLabels:
      app: subpath-nas-3
  template:
    metadata:
      labels:
        app: subpath-nas-3
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nas-pvc
              mountPath: "/data"
      volumes:
        - name: nas-pvc
          persistentVolumeClaim:
            claimName: nas-csi-pvc-subpath-3
