apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: c3
  template:
    metadata:
      labels:
        app: nginx
        component: c3
    spec:
      containers:
        - image: xishengcai/canary
          imagePullPolicy: IfNotPresent
          name: nginx
          env:
            - name: VERSION
              value: v3
          ports:
            - containerPort: 80
              name: port
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: c2
  template:
    metadata:
      labels:
        app: nginx
        component: c2
    spec:
      containers:
        - image: xishengcai/canary
          imagePullPolicy: IfNotPresent
          name: nginx
          env:
            - name: VERSION
              value: v2
          ports:
            - containerPort: 80
              name: port
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: c1
  template:
    metadata:
      labels:
        app: nginx
        component: c1
    spec:
      containers:
        - image: xishengcai/canary
          imagePullPolicy: IfNotPresent
          name: canary
          ports:
            - containerPort: 80
              name: port
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-c1
  namespace: test
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: c1
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: web-c3
  namespace: test
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: c3
  sessionAffinity: None
  type: NodePort
