apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-dr
  namespace: test
spec:
  host: web-svc
  subsets:
    - name: canary-v1
      labels:
        version: v1
    - name: canary-v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-virtual-svc
  namespace: test
spec:
  gateways:
    - test-web
    - mesh
  hosts:
    - web-svc
    - www.cai.com # 因为有了网格内的服务主机的定义，这里就不能用 * 了
  http:
    - route:
        - destination:
            host: web-svc
            version: v1
          weight: 0
        - destination:
            host: web-svc
            version: v2
          weight: 100
      match:
        - gateways:
            - test-web # 限制只对 Ingress 网关的流量有效
    - route:
        - destination:
            host: web-svc
            version: v1
          weight: 20
        - destination:
            host: web-svc
            version: v2
          weight: 50
      match:
        - gateways:
            - mesh # 对所有网格内服务有效
          uri:
            prefix: /
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-web
  namespace: test
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"


