apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ssl
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "test"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "tls-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - host: 'www.test.com'
      http:
        paths:
          - backend:
              serviceName: web-c1
              servicePort: 80
            path: /hello
